apiVersion: v1
kind: Service
metadata:
   name: be-identifier-service
   namespace: identifier-app
spec:
   selector:
      app: be-gan-identifier
   ports:
      - protocol: TCP
        port: 5000
        targetPort: 5000
   type: ClusterIP
